name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "libs/**.luau"
      - "testkit.luau"
  pull_request:
    branches: [ main ]
    paths:
      - "libs/**.luau"
      - "testkit.luau"

jobs:
  run-tests:
    strategy:
        fail-fast: false
        matrix:
          include:
            - name: Windows x86_64
              runner-os: windows-latest
  
            - name: Linux x86_64
              runner-os: ubuntu-latest
  
            - name: macOS aarch64
              runner-os: macos-14
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner-os }}
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Toolchain
        run: foreman install

      - name: Run Tests
        shell: bash
        run: |
          find libs -name "*test.luau" | while read -r file; do
            # append the finish call to the end of the file, because im lazy!!
            echo -e "\n\nassert(FINISH())" >> "$file"

            lune run $file
          done
