name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "scripts/diff_to_tbl.luau"
      - "scripts/test_runner.luau"
      - "scripts/depgraph.luau"
      - "testkit.luau"
  pull_request:
    branches: [ main ]
    paths:
      - "scripts/diff_to_tbl.luau"
      - "scripts/test_runner.luau"
      - "scripts/depgraph.luau"
      - "testkit.luau"

jobs:
  Main:    
    runs-on: ${{ matrix.runner-os }}
    name: ${{ matrix.name }}
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            runner-os: windows-latest
  
          - name: Linux
            runner-os: ubuntu-latest
  
          - name: macOS
            runner-os: macos-14
        
    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/checkout@v3

      - name: Install Toolchain
        run: rokit install --no-trust-check

      - name: Fetch diff
        id: fetch_diff
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "diff=(gh pr diff ${{ github.event.pull_request.number }})" >> .diff
          else
            echo "diff=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }} --header 'Accept: application/vnd.github.v3.diff')" >> .diff
          fi

      - name: Run test runner
        run: lune run scripts/test_runner
