name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    strategy:
        fail-fast: false
        matrix:
          include:
            - name: Windows x86_64
              runner-os: windows-latest
  
            - name: Linux x86_64
              runner-os: ubuntu-latest
  
            - name: macOS x86_64
              runner-os: macos-13
  
            - name: macOS aarch64
              runner-os: macos-14
    name: CI - ${{ matrix.name }}
    runs-on: ${{ matrix.runner-os }}
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Toolchain
        run: foreman install

      - name: Run Tests
        shell: bash
        run: |
          find libs -name "*test.luau" | while read -r file; do
            lune run $file
          done