name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "scripts/test_runner.luau"
      - "libs/**.luau"
      - "testkit.luau"
  pull_request:
    branches: [ main ]
    paths:
      - "scripts/test_runner.luau"
      - "libs/**.luau"
      - "testkit.luau"

jobs:
  Main:    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            runner-os: windows-latest
  
          - name: Linux
            runner-os: ubuntu-latest
  
          - name: macOS
            runner-os: macos-14

    concurrency:
      group: CI-${{ matrix.runner-os }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ${{ matrix.runner-os }}
    name: ${{ matrix.name }}
        
    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/checkout@v3

      - name: Get diff
        id: diff
        uses: ./.github/workflows/getdiff.yml

      - name: Run test runner
        run: lune run scripts/test_runner ${{ steps.diff.outputs.json }}
