name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Toolchain
        run: foreman install

      - name: Run Tests
        run: |
          find libs -name "*test.luau" | while read -r file; do
            echo "Running tests for library $file"
            lune "$file"
          done