name: get-diff
description: GitHub action to get the current repos diff
author: kalrnlo

inputs:
  token:
    description: "GitHub token via `github.token`"
    default: "${{ github.token }}"
    required: false

runs:
    using: "composite"
    outputs:
      json: ${{ steps.fetch.outputs.json }}
        
    steps:
      - uses: actions/checkout@v3
            
      - name: Fetch
        shell: bash
        id: fetch
        run: |
          echo "json=$(curl -O ${{ github.event.compare }} | jq)" >> $GITHUB_OUTPUT

branding:
  icon: link-2
  color: blue