name: Print diff

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  Main:
    runs-on: ubuntu-latest
        
    steps:
            - uses: actions/checkout@v2
            - uses: technote-space/get-diff-action@v6
              with:
                FORMAT: json
            - run: echo '${{ env.GIT_DIFF }}' | jq .