name: Release

on:
  release:
    types: [ created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false

  build-and-upload:
    needs: ["create-release"]
    runs-on: ubuntu-latest
    env:
      BIN: zap
    steps:
      - uses: actions/checkout@v3

      - name: Get Version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "PROJECT_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "PROJECT_VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          fi
          echo "Version is: ${{ env.PROJECT_VERSION }}"

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Toolchain
        run: foreman install

      - name: Run release script
        run: lune run release

      - name: Zip and Upload Subdirectories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd output
          for dir in */; do
            dir=${dir%/}
            zip -r "../${dir}.zip" "$dir"
            echo "Uploading ${dir}.zip"
            gh release upload ${{ github.ref_name }} "../${dir}.zip" --clobber
          done

      - name: Upload Individual Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd output
          for file in *; do
            if [ -f "$file" ]; then
              echo "Uploading $file"
              gh release upload ${{ github.ref_name }} "$file" --clobber
            fi
          done

      - name: Upload All as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BIN }}-${{ env.PROJECT_VERSION }}-all
          path: output