name: Release

on:
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "PROJECT_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "PROJECT_VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          fi
          echo "Version is: ${{ env.PROJECT_VERSION }}"

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Toolchain
        run: foreman install

      - name: Run release script
        run: lune run release

      - name: Upload libraries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd output
          for dir in */; do
            dir=${dir%/}
            zip -r "../${dir}.zip" "$dir"
            echo "Uploading ${dir}.zip"
            gh release upload ${{ github.ref_name }} "../${dir}.zip" --clobber
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rbxlibs-${{ env.PROJECT_VERSION }}-ALL-LIBS
          path: output