name: Release Libraries

on:
  workflow_dispatch:
    inputs:
      libs:
        description: 'List of libraries to force new releases for'
        required: true
        type: string
  push:
    branches: [ main ]
    paths:
      - "libs/**.luau"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/ci.yml

  Main:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Toolchain
        run: rokit install --no-trust-check

      - name: Fetch diff
        id: fetch_diff
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "diff=(gh pr diff ${{ github.event.pull_request.number }})" >> .diff
          else
            echo "diff=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }} --header 'Accept: application/vnd.github.v3.diff')" >> .diff
          fi

      - name: Run releases script
        run: lune run scripts/release/make_lib_releases ${{ inputs.libs }}
